# steps:
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/conductive-fold-275020/gke-backend:latest", "backend/"]
   
#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/conductive-fold-275020/gke-backend:latest"]

#   - name: "gcr.io/cloud-builders/docker"
#     args: ["build", "-t", "gcr.io/conductive-fold-275020/gke-frontend:latest", "frontend/"]

#   - name: "gcr.io/cloud-builders/docker"
#     args: ["push", "gcr.io/conductive-fold-275020/gke-frontend:latest"]

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f","deployment.yaml"]
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config


  - name: "gcr.io/cloud-builders/kubectl"
    args: ["expose", "deployment", "launch-app", "--type=LoadBalancer", "--name=launch-app-service"]
    env:
      - CLOUDSDK_COMPUTE_REGION=$_CUSTOM_REGION
      - CLOUDSDK_CONTAINER_CLUSTER=$_CUSTOM_CLUSTER
      - KUBECONFIG=/workspace/.kube/config

substitutions:
  _CUSTOM_REGION: us-central1-c
  _CUSTOM_CLUSTER: launch-cluster