apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-launch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gke-launch
  template:
    metadata:
      labels:
        app: gke-launch
    spec:
      containers:
      - name: frontend
        image: gcr.io/conductive-fold-275020/frontend:latest
        ports:
        - containerPort: 5000
      - name: backend
        image: gcr.io/conductive-fold-275020/backend:latest
        env:
        - name: dblake15
          value: "stolaunch"
        - name: capstoneproject
          value: "launchpass"
        - name: NAMESPACE
          value: "cir-anders-namespace"
        ports:
        - containerPort: 5001
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket-volume
        securityContext:
            privileged: true
      volumes:
        - name: docker-socket-volume
          hostPath:
              path: /var/run/docker.sock
              type: File
